# fly.toml app configuration file generated for backendmedimate2 on 2024-06-03T19:47:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backendmedimate"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[processes]
  web = "node index.js"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
