# fly.toml app configuration file generated for backendmedimate on 2024-06-10T18:21:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendmedimate'
primary_region = 'scl'

[build]

[processes]
  web = 'node index.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
